name: Remote Dispatch Responder
run-name: "Content: ${{ github.event.client_payload.commit_message }}"

on:
  repository_dispatch:
    types:
      - dispatch-publish

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ github.event.client_payload.token }}"
          submodules: "recursive"

      - uses: ./.github/actions/build


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
