name: Remote Dispatch Responder
run-name: "Content: ${{ github.event.client_payload.commit_message }}"

on:
  repository_dispatch:
    types:
      - dispatch-publish

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ github.event.client_payload.token }}"
          submodules: "recursive"

      - name: Update Submodules
        run: git submodule update --recursive --remote

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .svelte-kit
            build
          key: ${{ runner.os }}-vite-build-${{ hashFiles('build') }}
          restore-keys: ${{ runner.os }}-vite-build-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build with Vite
        env:
          ROOT_DIRECTORY: /home/runner/work/silicon/silicon/
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
